import mongoose from 'mongoose';
import dotenv from 'dotenv';
import Recipe from './models/Recipe.js';

dotenv.config();

const menuItems = [
    // Veg Starters
    { title: "Paneer Tikka", category: "Starter", time: "30", difficulty: "Medium", region: "Indian", dietType: "Vegetarian", ingredients: ["Paneer", "Yogurt", "Tikka Masala", "Capsicum", "Onion"], steps: ["Marinate paneer and veggies.", "Grill until charred.", "Serve hot with mint chutney."], calories: 250, protein: 14, carbs: 10, fat: 18, image: "" },
    { title: "Hara Bhara Kabab", category: "Starter", time: "40", difficulty: "Medium", region: "Indian", dietType: "Vegetarian", ingredients: ["Spinach", "Peas", "Potatoes", "Spices"], steps: ["Boil and mash veggies.", "Mix with spices and form patties.", "Shallow fry until crisp."], calories: 150, protein: 5, carbs: 20, fat: 6, image: "" },
    { title: "Veg Seekh Kabab", category: "Starter", time: "30", difficulty: "Medium", region: "Indian", dietType: "Vegetarian", ingredients: ["Mixed Veggies", "Gram Flour", "Spices", "Skewers"], steps: ["Mince vegetables.", "Bind with flour and spices.", "Mold on skewers and grill."], calories: 180, protein: 6, carbs: 22, fat: 8, image: "" },
    { title: "Dahi ke Kabab", category: "Starter", time: "25", difficulty: "Medium", region: "Indian", dietType: "Vegetarian", ingredients: ["Hung Curd", "Paneer", "Gram Flour", "Spices"], steps: ["Mix hung curd and spices.", "Form soft patties.", "Shallow fry gently."], calories: 200, protein: 8, carbs: 15, fat: 12, image: "" },
    { title: "Tandoori Mushroom", category: "Starter", time: "25", difficulty: "Easy", region: "Indian", dietType: "Vegetarian", ingredients: ["Mushrooms", "Yogurt", "Tandoori Masala"], steps: ["Marinate mushrooms in yogurt and spices.", "Roast in tandoor or oven.", "Serve with onion rings."], calories: 120, protein: 4, carbs: 10, fat: 7, image: "" },
    { title: "Aloo Tikki", category: "Starter", time: "25", difficulty: "Easy", region: "Street Food", dietType: "Vegetarian", ingredients: ["Potatoes", "Peas", "Spices", "Chaat Masala"], steps: ["Mash boiled potatoes and peas.", "Make patties and shallow fry.", "Serve as chaat or snack."], calories: 220, protein: 3, carbs: 30, fat: 10, image: "" },

    // Non-Veg Starters
    { title: "Tandoori Chicken", category: "Starter", time: "45", difficulty: "Medium", region: "Indian", dietType: "High Protein", ingredients: ["Chicken", "Yogurt", "Tandoori Spices", "Lemon"], steps: ["Make cuts in chicken.", "Marinate overnight with yogurt and spices.", "Grill in tandoor until cooked."], calories: 280, protein: 35, carbs: 5, fat: 12, image: "" },
    { title: "Chicken Tikka", category: "Starter", time: "35", difficulty: "Medium", region: "Indian", dietType: "High Protein", ingredients: ["Boneless Chicken", "Yogurt", "Spices"], steps: ["Marinate chicken chunks.", "Skewer and grill.", "Serve with mint dip."], calories: 240, protein: 30, carbs: 4, fat: 10, image: "" },
    { title: "Mutton Seekh Kebab", category: "Starter", time: "40", difficulty: "Hard", region: "Indian", dietType: "High Protein", ingredients: ["Minced Mutton", "Onions", "Garam Masala", "Coriander"], steps: ["Mix minced meat with spices.", "Shape tightly around skewers.", "Grill over hot coals."], calories: 310, protein: 28, carbs: 3, fat: 20, image: "" },
    { title: "Fish Tikka", category: "Starter", time: "30", difficulty: "Medium", region: "Indian", dietType: "Healthy", ingredients: ["White Fish Fillets", "Ajwain", "Yogurt", "Mustard Oil"], steps: ["Cut fish into cubes.", "Apply marinade gently.", "Grill or bake until flaky."], calories: 200, protein: 25, carbs: 2, fat: 9, image: "" },
    { title: "Chicken Lollipop", category: "Starter", time: "40", difficulty: "Medium", region: "Chinese", dietType: "High Protein", ingredients: ["Chicken Wings", "Ginger Garlic Paste", "Soy Sauce", "Cornstarch"], steps: ["French the chicken wings.", "Batter coat the wings.", "Deep fry until crispy."], calories: 350, protein: 22, carbs: 15, fat: 24, image: "" },

    // Veg Main Course
    { title: "Kadai Paneer", category: "Main Course", time: "35", difficulty: "Medium", region: "Indian", dietType: "Vegetarian", ingredients: ["Paneer", "Capsicum", "Onions", "Kadai Masala", "Tomatoes"], steps: ["Dry roast and grind kadai masala.", "Sauté veggies and tomatoes.", "Add paneer and toss with masala."], calories: 320, protein: 15, carbs: 18, fat: 22, image: "" },
    { title: "Palak Paneer", category: "Main Course", time: "40", difficulty: "Medium", region: "Indian", dietType: "Healthy", ingredients: ["Spinach", "Paneer", "Garlic", "Cream"], steps: ["Blanch and puree spinach.", "Temper garlic and onions.", "Simmer paneer in spinach gravy."], calories: 280, protein: 16, carbs: 12, fat: 20, image: "" },
    { title: "Paneer Tikka Masala", category: "Main Course", time: "45", difficulty: "Medium", region: "Indian", dietType: "Vegetarian", ingredients: ["Grilled Paneer Tikka", "Tomato Gravy", "Cream", "Butter"], steps: ["Prepare paneer tikka.", "Make a rich tomato-onion gravy.", "Simmer tikka in gravy."], calories: 400, protein: 16, carbs: 20, fat: 28, image: "" },
    { title: "Dal Makhani", category: "Main Course", time: "120", difficulty: "Medium", region: "Punjabi", dietType: "Vegetarian", ingredients: ["Whole Black Urad Dal", "Kidney Beans", "Butter", "Cream", "Tomato Puree"], steps: ["Slow cook lentils overnight.", "Temper with garlic and tomato.", "Finish with cream and butter."], calories: 350, protein: 12, carbs: 35, fat: 18, image: "" },
    { title: "Dal Fry", category: "Main Course", time: "30", difficulty: "Easy", region: "Indian", dietType: "Healthy", ingredients: ["Toor Dal", "Onion", "Tomato", "Jeera", "Ghee"], steps: ["Boil dal until soft.", "Make a spicy onion-tomato tadka.", "Pour tadka over dal."], calories: 180, protein: 9, carbs: 28, fat: 5, image: "" },
    { title: "Malai Kofta", category: "Main Course", time: "50", difficulty: "Hard", region: "Indian", dietType: "Vegetarian", ingredients: ["Paneer", "Potatoes", "Cashew Gravy", "Cream"], steps: ["Make paneer-potato balls and fry.", "Prepare a sweet cashew-onion gravy.", "Place koftas in gravy before serving."], calories: 450, protein: 12, carbs: 30, fat: 32, image: "" },
    { title: "Mix Veg", category: "Main Course", time: "35", difficulty: "Easy", region: "Indian", dietType: "Healthy", ingredients: ["Carrots", "Beans", "Cauliflower", "Peas", "Spices"], steps: ["Chop veggies.", "Sauté with Indian spices until tender.", "Garnish with coriander."], calories: 150, protein: 4, carbs: 20, fat: 6, image: "" },
    { title: "Veg Jalfrezi", category: "Main Course", time: "30", difficulty: "Medium", region: "Indian", dietType: "Vegetarian", ingredients: ["Mixed Veggies", "Tomato Base", "Vinegar", "Chilies"], steps: ["Stir fry vegetables on high heat.", "Toss with a tangy, spicy tomato sauce.", "Serve hot."], calories: 180, protein: 5, carbs: 22, fat: 8, image: "" },

    // Non-Veg Main Course
    { title: "Butter Chicken", category: "Main Course", time: "50", difficulty: "Medium", region: "Punjabi", dietType: "High Protein", ingredients: ["Tandoori Chicken", "Tomatoes", "Butter", "Cream", "Kasuri Methi"], steps: ["Make a smooth tomato makhani sauce.", "Add cooked tandoori chicken pieces.", "Mix in butter and cream. Simmer."], calories: 480, protein: 28, carbs: 12, fat: 35, image: "" },
    { title: "Chicken Curry", category: "Main Course", time: "45", difficulty: "Easy", region: "Indian", dietType: "High Protein", ingredients: ["Chicken with bone", "Onion", "Tomatoes", "Ginger Garlic", "Curry Spices"], steps: ["Brown onions and spices.", "Add chicken and sear.", "Add water and slow cook until tender."], calories: 320, protein: 30, carbs: 10, fat: 16, image: "" },
    { title: "Kadai Chicken", category: "Main Course", time: "40", difficulty: "Medium", region: "Indian", dietType: "High Protein", ingredients: ["Chicken", "Kadai Masala", "Capsicum", "Onion"], steps: ["Roast kadai spices.", "Cook chicken with chunky bell peppers and onions.", "Simmer until done."], calories: 340, protein: 32, carbs: 12, fat: 18, image: "" },
    { title: "Chicken Bhuna", category: "Main Course", time: "50", difficulty: "Hard", region: "Indian", dietType: "High Protein", ingredients: ["Chicken", "Lots of Onions", "Whole Spices", "Yogurt"], steps: ["Slow cook chicken in its own juices.", "Continuously roast (bhuna) the masala until dry and dark.", "Garnish with ginger juliennes."], calories: 380, protein: 34, carbs: 10, fat: 22, image: "" },
    { title: "Mutton Rogan Josh", category: "Main Course", time: "90", difficulty: "Hard", region: "Indian", dietType: "High Protein", ingredients: ["Mutton", "Kashmiri Red Chili", "Fennel Powder", "Yogurt"], steps: ["Brown mutton in oil/ghee.", "Add yogurt and specific Kashmiri spices.", "Slow cook until meat falls off the bone."], calories: 450, protein: 28, carbs: 8, fat: 32, image: "" },
    { title: "Mutton Seekh Masala", category: "Main Course", time: "45", difficulty: "Medium", region: "Indian", dietType: "High Protein", ingredients: ["Mutton Seekh Kebabs", "Onion-Tomato Gravy", "Spices"], steps: ["Chop cooked seekh kebabs.", "Prepare a spicy masala base.", "Toss the kebabs in the masala."], calories: 420, protein: 25, carbs: 12, fat: 28, image: "" },
    { title: "Fish Curry", category: "Main Course", time: "30", difficulty: "Medium", region: "Bengali", dietType: "Healthy", ingredients: ["Fish", "Mustard Oil", "Mustard Seeds", "Tomatoes"], steps: ["Fry fish lightly.", "Make a mustard and tomato based broth.", "Simmer fish in broth."], calories: 280, protein: 26, carbs: 8, fat: 15, image: "" },

    // Indian Breads
    { title: "Roti", category: "Breakfast", time: "10", difficulty: "Easy", region: "Indian", dietType: "Healthy", ingredients: ["Whole Wheat Flour", "Water"], steps: ["Knead soft dough.", "Roll into circles.", "Cook on hot tawa until puffy."], calories: 100, protein: 3, carbs: 22, fat: 1, image: "" },
    { title: "Butter Roti", category: "Breakfast", time: "10", difficulty: "Easy", region: "Indian", dietType: "Vegetarian", ingredients: ["Whole Wheat Flour", "Water", "Butter"], steps: ["Make classic roti.", "Smear with butter while hot."], calories: 130, protein: 3, carbs: 22, fat: 4, image: "" },
    { title: "Naan", category: "Breakfast", time: "15", difficulty: "Medium", region: "Indian", dietType: "Vegetarian", ingredients: ["All-purpose flour", "Yeast/Baking Powder", "Yogurt"], steps: ["Knead and rest dough.", "Roll into teardrop shape.", "Bake in tandoor or hot tawa/oven."], calories: 250, protein: 6, carbs: 45, fat: 5, image: "" },
    { title: "Garlic Naan", category: "Breakfast", time: "20", difficulty: "Medium", region: "Indian", dietType: "Vegetarian", ingredients: ["Naan dough", "Minced Garlic", "Coriander", "Butter"], steps: ["Press garlic and coriander into rolled dough.", "Bake.", "Brush with melted butter."], calories: 280, protein: 6, carbs: 45, fat: 8, image: "" },
    { title: "Kulcha", category: "Breakfast", time: "20", difficulty: "Medium", region: "Indian", dietType: "Vegetarian", ingredients: ["Refined Flour", "Baking soda", "Yogurt"], steps: ["Prepare soft dough.", "Cook until fluffy and golden.", "Serve with chole."], calories: 260, protein: 5, carbs: 48, fat: 4, image: "" },
    { title: "Laccha Paratha", category: "Breakfast", time: "25", difficulty: "Hard", region: "Indian", dietType: "Vegetarian", ingredients: ["Whole Wheat Flour", "Ghee"], steps: ["Roll dough, smear ghee, and pleat.", "Roll again into a circle.", "Roast until layers separate and turn crispy."], calories: 240, protein: 4, carbs: 35, fat: 10, image: "" },
    { title: "Aloo Paratha", category: "Breakfast", time: "25", difficulty: "Medium", region: "Punjabi", dietType: "Vegetarian", ingredients: ["Wheat Dough", "Mashed Spiced Potatoes", "Butter"], steps: ["Stuff dough ball with potato mixture.", "Roll gently.", "Roast on tawa with ghee/butter."], calories: 300, protein: 6, carbs: 45, fat: 11, image: "" },

    // Rice & Biryani
    { title: "Veg Biryani", category: "Main Course", time: "60", difficulty: "Hard", region: "Indian", dietType: "Vegetarian", ingredients: ["Basmati Rice", "Mixed Veggies", "Biryani Spices", "Saffron"], steps: ["Parboil rice.", "Cook spicy veg gravy.", "Layer rice and veg, seal, and dum cook."], calories: 350, protein: 8, carbs: 55, fat: 10, image: "" },
    { title: "Chicken Biryani", category: "Main Course", time: "75", difficulty: "Hard", region: "Indian", dietType: "High Protein", ingredients: ["Basmati Rice", "Chicken", "Yogurt", "Biryani Spices", "Fried Onions"], steps: ["Marinate chicken.", "Layer partially cooked rice over chicken.", "Cook on dum (slow heat) for 40 mins."], calories: 450, protein: 25, carbs: 50, fat: 18, image: "" },
    { title: "Mutton Biryani", category: "Main Course", time: "90", difficulty: "Hard", region: "Indian", dietType: "High Protein", ingredients: ["Basmati Rice", "Mutton", "Spices", "Ghee"], steps: ["Cook mutton tenderly with spices.", "Layer with rice, saffron, and mint.", "Dum cook."], calories: 550, protein: 28, carbs: 50, fat: 25, image: "" },
    { title: "Jeera Rice", category: "Main Course", time: "20", difficulty: "Easy", region: "Indian", dietType: "Healthy", ingredients: ["Basmati Rice", "Cumin Seeds (Jeera)", "Ghee"], steps: ["Wash rice.", "Temper ghee with cumin seeds.", "Cook rice in tempered water."], calories: 210, protein: 4, carbs: 40, fat: 5, image: "" },
    { title: "Steam Rice", category: "Main Course", time: "15", difficulty: "Easy", region: "Global", dietType: "Vegan", ingredients: ["White Rice", "Water"], steps: ["Wash rice.", "Boil or steam until fluffy."], calories: 150, protein: 3, carbs: 35, fat: 0, image: "" },

    // South Indian Staples
    { title: "Masala Dosa", category: "Breakfast", time: "30", difficulty: "Hard", region: "South Indian", dietType: "Vegetarian", ingredients: ["Dosa Batter", "Potato Masala", "Chutney", "Oil"], steps: ["Spread thin batter on hot tawa.", "Cook until crisp.", "Place potato filling in center and fold."], calories: 280, protein: 6, carbs: 45, fat: 9, image: "" },
    { title: "Idli", category: "Breakfast", time: "20", difficulty: "Easy", region: "South Indian", dietType: "Healthy", ingredients: ["Idli Batter", "Water"], steps: ["Pour batter into idli molds.", "Steam for 10-15 minutes.", "Serve soft idlis with sambhar."], calories: 120, protein: 4, carbs: 24, fat: 0, image: "" },
    { title: "Medu Vada", category: "Snacks", time: "30", difficulty: "Medium", region: "South Indian", dietType: "Vegetarian", ingredients: ["Urad Dal Batter", "Curry Leaves", "Green Chilies", "Oil"], steps: ["Whip batter until fluffy.", "Form donut shapes.", "Deep fry until golden."], calories: 250, protein: 7, carbs: 30, fat: 12, image: "" },
    { title: "Uttapam", category: "Breakfast", time: "20", difficulty: "Easy", region: "South Indian", dietType: "Vegetarian", ingredients: ["Dosa Batter", "Onions", "Tomatoes", "Coriander"], steps: ["Pour thick layer of batter.", "Top with chopped veggies.", "Cook both sides."], calories: 200, protein: 5, carbs: 35, fat: 4, image: "" },
    { title: "Sambhar", category: "Breakfast", time: "40", difficulty: "Medium", region: "South Indian", dietType: "Healthy", ingredients: ["Toor Dal", "Tamarind", "Sambhar Powder", "Mixed Veggies"], steps: ["Boil dal with veggies.", "Add tamarind extract and spices.", "Temper with mustard seeds and curry leaves."], calories: 150, protein: 6, carbs: 25, fat: 3, image: "" },

    // Accompaniments & Desserts
    { title: "Mixed Veg Raita", category: "Snacks", time: "10", difficulty: "Easy", region: "Indian", dietType: "Healthy", ingredients: ["Yogurt", "Cucumber", "Tomato", "Onion", "Roasted Cumin Powder"], steps: ["Whisk yogurt.", "Mix in finely chopped veggies.", "Sprinkle cumin and salt."], calories: 80, protein: 4, carbs: 8, fat: 3, image: "" },
    { title: "Boondi Raita", category: "Snacks", time: "10", difficulty: "Easy", region: "Indian", dietType: "Vegetarian", ingredients: ["Yogurt", "Crispy Boondi", "Spices"], steps: ["Soak boondi lightly in warm water (optional).", "Mix into whisked spiced yogurt.", "Serve chilled."], calories: 120, protein: 4, carbs: 12, fat: 6, image: "" },
    { title: "Green Salad", category: "Starter", time: "10", difficulty: "Easy", region: "Global", dietType: "Vegan", ingredients: ["Cucumber", "Tomato", "Onion", "Carrot", "Lemon"], steps: ["Slice all vegetables.", "Arrange nicely on a plate.", "Squeeze lemon juice over them."], calories: 40, protein: 1, carbs: 9, fat: 0, image: "" },
    { title: "Papad", category: "Starter", time: "5", difficulty: "Easy", region: "Indian", dietType: "Vegan", ingredients: ["Lentil Papad"], steps: ["Roast over direct flame or fry in oil."], calories: 30, protein: 2, carbs: 5, fat: 0, image: "" },
    { title: "Gulab Jamun", category: "Desserts", time: "45", difficulty: "Medium", region: "Indian", dietType: "Vegetarian", ingredients: ["Khoya", "Refined Flour", "Sugar Syrup", "Cardamom"], steps: ["Make dough balls.", "Deep fry on very low heat.", "Soak in hot sugar syrup."], calories: 300, protein: 5, carbs: 45, fat: 12, image: "" },
    { title: "Rasmalai", category: "Desserts", time: "60", difficulty: "Hard", region: "Indian", dietType: "Vegetarian", ingredients: ["Paneer/Chhena", "Milk", "Sugar", "Saffron"], steps: ["Make paneer discs.", "Boil in sugar syrup.", "Soak in thickened sweetened saffron milk."], calories: 250, protein: 8, carbs: 30, fat: 10, image: "" },
    { title: "Kulfi", category: "Desserts", time: "180", difficulty: "Medium", region: "Indian", dietType: "Vegetarian", ingredients: ["Full Fat Milk", "Sugar", "Nuts", "Cardamom"], steps: ["Reduce milk until thick.", "Add sugar and nuts.", "Freeze in molds."], calories: 220, protein: 6, carbs: 25, fat: 11, image: "" },
    { title: "Gajar Halwa", category: "Desserts", time: "60", difficulty: "Medium", region: "Indian", dietType: "Vegetarian", ingredients: ["Carrots", "Milk", "Sugar", "Ghee", "Nuts"], steps: ["Grate carrots.", "Cook slowly in milk until dry.", "Roast in ghee and add sugar."], calories: 350, protein: 5, carbs: 42, fat: 18, image: "" },

    // Beverages
    { title: "Masala Chai", category: "Breakfast", time: "15", difficulty: "Easy", region: "Indian", dietType: "Vegetarian", ingredients: ["Water", "Milk", "Tea Leaves", "Ginger", "Cardamom", "Sugar"], steps: ["Boil water with ginger and cardamom.", "Add tea leaves and simmer.", "Add milk, boil up, and strain."], calories: 100, protein: 3, carbs: 15, fat: 3, image: "" },
    { title: "Sweet Lassi", category: "Breakfast", time: "5", difficulty: "Easy", region: "Punjabi", dietType: "Vegetarian", ingredients: ["Yogurt", "Sugar", "Water", "Ice"], steps: ["Blend yogurt, sugar, and water.", "Serve chilled in a tall glass."], calories: 180, protein: 6, carbs: 28, fat: 5, image: "" },
    { title: "Salted Lassi", category: "Breakfast", time: "5", difficulty: "Easy", region: "Punjabi", dietType: "Healthy", ingredients: ["Yogurt", "Water", "Roasted Cumin", "Salt"], steps: ["Whisk yogurt with water.", "Add spices and mix.", "Serve chilled."], calories: 90, protein: 6, carbs: 8, fat: 4, image: "" },
    { title: "Buttermilk (Chaas)", category: "Breakfast", time: "5", difficulty: "Easy", region: "Indian", dietType: "Healthy", ingredients: ["Yogurt", "Water", "Mint Leaves", "Cumin", "Black Salt"], steps: ["Blend highly diluted yogurt with spices.", "Garnish with mint.", "Serve chilled."], calories: 45, protein: 3, carbs: 5, fat: 2, image: "" },
    { title: "Fresh Lime Soda", category: "Breakfast", time: "5", difficulty: "Easy", region: "Indian", dietType: "Vegan", ingredients: ["Lemon/Lime", "Club Soda", "Sugar", "Salt", "Ice"], steps: ["Squeeze lime juice into glass.", "Add salt and sugar.", "Top with club soda and stir."], calories: 60, protein: 0, carbs: 15, fat: 0, image: "" }
];

const seedMenu = async () => {
    try {
        if (!process.env.MONGO_URI) {
            console.error('MONGO_URI is missing in .env');
            process.exit(1);
        }
        await mongoose.connect(process.env.MONGO_URI);
        console.log('Connected to MongoDB via seed script...');

        await Recipe.insertMany(menuItems);

        console.log(`✅ Successfully added ${menuItems.length} Giant Menu recipes to Database without images!`);
        process.exit(0);
    } catch (err) {
        console.error('Failed to inject recipes', err);
        process.exit(1);
    }
};

seedMenu();
